// admin/src/Components/Posts/PostDetailsTemplateComponent.tsx
import React from "react";
import {PostDetailsModel} from "../../Models/Posts/PostDetailsModel";
import axios from "../../Api/axios";
import { useHistory } from "react-router-dom";
import {routes} from "../../Routes/Routes";

interface IPostDetailsTemplateComponentProps {
    postDetailsModel: PostDetailsModel;
}

const PostDetailsTemplateComponent = (props: IPostDetailsTemplateComponentProps) => {
    const post = props.postDetailsModel;
    const history = useHistory();
    const approvePost = async (id: number) => {
        await axios.post(`${process.env.REACT_APP_BACKEND_URL}/api/posts/approve/${id}`);
        history.push(routes.home);
    };
    return (
        <div className="flex-column">
            <h2>{post.title}</h2>
            <div>{post.description}</div>
            {
                post.imageUrls.map((u, i) => {
                    return (
                        <img src={u} alt="image" key={`image_${i}`} className="mx-auto d-block"/>
                    );
                })
            }
            <button className="btn btn-primary float-right" onClick={() => approvePost(post.id)}>Approve</button>
            <button className="btn btn-danger float-right">Disapprove</button>
            <button className="btn btn-primary float-right">Back To List</button>
        </div>
    )
};

export default PostDetailsTemplateComponent;

// public/src/app/Components/Posts/post-details-template/post-details-template.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {PostDetailsModel} from '../../../Models/Posts/PostDetailsModel';
import {Routes} from '../../../Routes/routes';

@Component({
    selector: 'app-post-details-template',
    templateUrl: './post-details-template.component.html',
    styleUrls: ['./post-details-template.component.css']
})
export class PostDetailsTemplateComponent implements OnInit {
    @Input() postDetailsModel: PostDetailsModel;
    routes = Routes;
    constructor() { }

    ngOnInit(): void {
    }

}

<div class="flex-column">
    <h2>{{postDetailsModel.title}}</h2>
    <div>{{postDetailsModel.description}}</div>
    <img *ngFor="let image of postDetailsModel.imageUrls" src="{{image}}" alt="image" class="mx-auto d-block">
    <button class="btn btn-primary float-right" routerLink="/{{routes.myPosts}}">Back to List</button>
</div>
